### ISSUE TITLE
Isolate Crypto Interface for KMMP purposes

### ISSUE THREAD

**Issue by tmspzz** [wireapp/kalium#102]
Look into: https://github.com/touchlab/cklib

- [ ] Expand Crypto Module to Cover iOS as well

**Comment by vitorhugods** [comment]
`cklib` seems to have a different purpose and is getting kinda deprecated for now.

If we want to bundle native cryptography code into Kalium, I think our best bet for the future is including a library (be it `.a`, or `.so`) into the project, adding them to the `.def` kotlin/native files and wrapping the calls for multiple platforms.

I couldn't find any straight up answers for this after a lot of research. But in any case, isolating a Crypto interface is a must for now in order to build for mobile.
